stages:
  - build

# Build and push the Docker image to the GitLab image registry
# using Podman.
podman-build:
  stage: build

  image:
    name: $CI_REGISTRY/quayio/podman/stable

  before_script:
    - mkdir -p /run/containers/0
    - echo $DOCKER_AUTH_CONFIG > /run/containers/0/auth.json

  script:
    # GitLab has a built-in Docker image registry, whose
    # parameters are set automatically. You can use some
    # other Docker registry though by changing the login and
    # image name.
    - podman build -t "$CI_REGISTRY/docker/ocp4-ansible-devops:latest" .
    - podman push "$CI_REGISTRY/docker/ocp4-ansible-devops:latest"
