---

- name: Gather all the Pods with error state
  shell: "oc get pods -A | grep -E "iptables-alerter|dns-default|Error" | awk '{print $1\" \"$2}'"
  register: error_pods

- name: Delete Pods with error state
  shell: "oc delete pod -n {{ item }}"
  loop: "{{ error_pods.stdout_lines }}"
